export const FOURMEME_ABI = [
    {
        inputs: [
            { name: "token", type: "address" },
            { name: "to", type: "address" },
            { name: "funds", type: "uint256" },
            { name: "minAmount", type: "uint256" },
        ],
        name: "buyTokenAMAP",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            { name: "token", type: "address" },
            { name: "amount", type: "uint256" },
            { name: "maxFunds", type: "uint256" },
        ],
        name: "buyToken",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            { name: "args", type: "bytes" },
            { name: "time", type: "uint256" },
            { name: "signature", type: "bytes" },
        ],
        name: "buyToken",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            { name: "token", type: "address" },
            { name: "amount", type: "uint256" },
            { name: "minFunds", type: "uint256" },
        ],
        name: "sellToken",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { name: "origin", type: "uint256" },
            { name: "token", type: "address" },
            { name: "to", type: "address" },
            { name: "funds", type: "uint256" },
            { name: "minAmount", type: "uint256" },
        ],
        name: "buyWithEth",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            { name: "origin", type: "uint256" },
            { name: "token", type: "address" },
            { name: "from", type: "address" },
            { name: "amount", type: "uint256" },
            { name: "minFunds", type: "uint256" },
        ],
        name: "sellForEth",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ name: "", type: "address" }],
        name: "_tokenInfos",
        outputs: [
            { name: "base", type: "address" },
            { name: "quote", type: "address" },
            { name: "template", type: "uint256" },
            { name: "totalSupply", type: "uint256" },
            { name: "maxOffers", type: "uint256" },
            { name: "maxRaising", type: "uint256" },
            { name: "launchTime", type: "uint256" },
            { name: "offers", type: "uint256" },
            { name: "funds", type: "uint256" },
            { name: "lastPrice", type: "uint256" },
            { name: "K", type: "uint256" },
            { name: "T", type: "uint256" },
            { name: "status", type: "uint256" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    { name: "base", type: "address" },
                    { name: "quote", type: "address" },
                    { name: "template", type: "uint256" },
                    { name: "totalSupply", type: "uint256" },
                    { name: "maxOffers", type: "uint256" },
                    { name: "maxRaising", type: "uint256" },
                    { name: "launchTime", type: "uint256" },
                    { name: "offers", type: "uint256" },
                    { name: "funds", type: "uint256" },
                    { name: "lastPrice", type: "uint256" },
                    { name: "K", type: "uint256" },
                    { name: "T", type: "uint256" },
                    { name: "status", type: "uint256" },
                ],
                name: "ti",
                type: "tuple",
            },
            { name: "funds", type: "uint256" },
        ],
        name: "calcBuyAmount",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "pure",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    { name: "base", type: "address" },
                    { name: "quote", type: "address" },
                    { name: "template", type: "uint256" },
                    { name: "totalSupply", type: "uint256" },
                    { name: "maxOffers", type: "uint256" },
                    { name: "maxRaising", type: "uint256" },
                    { name: "launchTime", type: "uint256" },
                    { name: "offers", type: "uint256" },
                    { name: "funds", type: "uint256" },
                    { name: "lastPrice", type: "uint256" },
                    { name: "K", type: "uint256" },
                    { name: "T", type: "uint256" },
                    { name: "status", type: "uint256" },
                ],
                name: "ti",
                type: "tuple",
            },
            { name: "amount", type: "uint256" },
        ],
        name: "calcBuyCost",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "pure",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    { name: "base", type: "address" },
                    { name: "quote", type: "address" },
                    { name: "template", type: "uint256" },
                    { name: "totalSupply", type: "uint256" },
                    { name: "maxOffers", type: "uint256" },
                    { name: "maxRaising", type: "uint256" },
                    { name: "launchTime", type: "uint256" },
                    { name: "offers", type: "uint256" },
                    { name: "funds", type: "uint256" },
                    { name: "lastPrice", type: "uint256" },
                    { name: "K", type: "uint256" },
                    { name: "T", type: "uint256" },
                    { name: "status", type: "uint256" },
                ],
                name: "ti",
                type: "tuple",
            },
            { name: "amount", type: "uint256" },
        ],
        name: "calcSellCost",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "pure",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    { name: "base", type: "address" },
                    { name: "quote", type: "address" },
                    { name: "template", type: "uint256" },
                    { name: "totalSupply", type: "uint256" },
                    { name: "maxOffers", type: "uint256" },
                    { name: "maxRaising", type: "uint256" },
                    { name: "launchTime", type: "uint256" },
                    { name: "offers", type: "uint256" },
                    { name: "funds", type: "uint256" },
                    { name: "lastPrice", type: "uint256" },
                    { name: "K", type: "uint256" },
                    { name: "T", type: "uint256" },
                    { name: "status", type: "uint256" },
                ],
                name: "ti",
                type: "tuple",
            },
            { name: "funds", type: "uint256" },
        ],
        name: "calcTradingFee",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
];
export const PANCAKE_ROUTER_ABI = [
    {
        inputs: [
            { name: "amountIn", type: "uint256" },
            { name: "path", type: "address[]" },
        ],
        name: "getAmountsOut",
        outputs: [{ name: "amounts", type: "uint256[]" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { name: "amountOutMin", type: "uint256" },
            { name: "path", type: "address[]" },
            { name: "to", type: "address" },
            { name: "deadline", type: "uint256" },
        ],
        name: "swapExactETHForTokens",
        outputs: [{ name: "amounts", type: "uint256[]" }],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            { name: "amountIn", type: "uint256" },
            { name: "amountOutMin", type: "uint256" },
            { name: "path", type: "address[]" },
            { name: "to", type: "address" },
            { name: "deadline", type: "uint256" },
        ],
        name: "swapExactTokensForETH",
        outputs: [{ name: "amounts", type: "uint256[]" }],
        stateMutability: "nonpayable",
        type: "function",
    },
];
export const AGGREGATOR_ABI = [
    {
        inputs: [],
        name: "FOUR_MEME_CHECKER",
        outputs: [
            { internalType: "address", name: "", type: "address" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "PANCAKE_V2_FACTORY",
        outputs: [
            { internalType: "address", name: "", type: "address" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "PANCAKE_V2_ROUTER",
        outputs: [
            { internalType: "address", name: "", type: "address" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "TOKEN_MANAGER2",
        outputs: [
            { internalType: "address", name: "", type: "address" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "TOKEN_MANAGER_HELPER3",
        outputs: [
            { internalType: "address", name: "", type: "address" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "USDT",
        outputs: [
            { internalType: "address", name: "", type: "address" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "WALLET_HELPER",
        outputs: [
            { internalType: "address", name: "", type: "address" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "WBNB",
        outputs: [
            { internalType: "address", name: "", type: "address" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "token", type: "address" }],
        name: "getFourmemeTokenInfo",
        outputs: [
            {
                components: [
                    {
                        components: [
                            { internalType: "string", name: "name", type: "string" },
                            { internalType: "string", name: "symbol", type: "string" },
                            { internalType: "uint8", name: "decimals", type: "uint8" },
                            { internalType: "uint256", name: "totalSupply", type: "uint256" },
                            { internalType: "bool", name: "isFourMemeToken", type: "bool" },
                        ],
                        internalType: "struct TokenInfoAggregator.BasicTokenInfo",
                        name: "basic",
                        type: "tuple",
                    },
                    {
                        components: [
                            { internalType: "uint256", name: "version", type: "uint256" },
                            { internalType: "address", name: "tokenManager", type: "address" },
                            { internalType: "address", name: "quote", type: "address" },
                            { internalType: "uint256", name: "lastPrice", type: "uint256" },
                            { internalType: "uint256", name: "usdPrice", type: "uint256" },
                            { internalType: "uint256", name: "tradingFeeRate", type: "uint256" },
                            { internalType: "uint256", name: "minTradingFee", type: "uint256" },
                            { internalType: "uint256", name: "launchTime", type: "uint256" },
                            { internalType: "uint8", name: "tradingStatus", type: "uint8" },
                        ],
                        internalType: "struct TokenInfoAggregator.PlatformInfo",
                        name: "platform",
                        type: "tuple",
                    },
                    {
                        components: [
                            { internalType: "uint256", name: "offers", type: "uint256" },
                            { internalType: "uint256", name: "maxOffers", type: "uint256" },
                            { internalType: "uint256", name: "funds", type: "uint256" },
                            { internalType: "uint256", name: "maxFunds", type: "uint256" },
                            { internalType: "bool", name: "liquidityAdded", type: "bool" },
                            { internalType: "uint256", name: "offerPercentage", type: "uint256" },
                            { internalType: "uint256", name: "fundsPercentage", type: "uint256" },
                        ],
                        internalType: "struct TokenInfoAggregator.TradingInfo",
                        name: "trading",
                        type: "tuple",
                    },
                    {
                        components: [
                            { internalType: "string", name: "quoteName", type: "string" },
                            { internalType: "string", name: "quoteSymbol", type: "string" },
                            { internalType: "uint8", name: "quoteDecimals", type: "uint8" },
                            { internalType: "uint256", name: "poolTokenBalance", type: "uint256" },
                            { internalType: "uint256", name: "poolQuoteBalance", type: "uint256" },
                            { internalType: "bool", name: "isXMode", type: "bool" },
                            { internalType: "uint256", name: "template", type: "uint256" },
                            {
                                components: [
                                    { internalType: "address", name: "pair", type: "address" },
                                    {
                                        components: [
                                            { internalType: "address", name: "token", type: "address" },
                                            { internalType: "uint256", name: "reserve", type: "uint256" },
                                        ],
                                        internalType: "struct TokenInfoAggregator.TokenReserveKV",
                                        name: "reserve0",
                                        type: "tuple",
                                    },
                                    {
                                        components: [
                                            { internalType: "address", name: "token", type: "address" },
                                            { internalType: "uint256", name: "reserve", type: "uint256" },
                                        ],
                                        internalType: "struct TokenInfoAggregator.TokenReserveKV",
                                        name: "reserve1",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct TokenInfoAggregator.V2PairInfo",
                                name: "v2TokenQuotePair",
                                type: "tuple",
                            },
                            {
                                components: [
                                    { internalType: "address", name: "pair", type: "address" },
                                    {
                                        components: [
                                            { internalType: "address", name: "token", type: "address" },
                                            { internalType: "uint256", name: "reserve", type: "uint256" },
                                        ],
                                        internalType: "struct TokenInfoAggregator.TokenReserveKV",
                                        name: "reserve0",
                                        type: "tuple",
                                    },
                                    {
                                        components: [
                                            { internalType: "address", name: "token", type: "address" },
                                            { internalType: "uint256", name: "reserve", type: "uint256" },
                                        ],
                                        internalType: "struct TokenInfoAggregator.TokenReserveKV",
                                        name: "reserve1",
                                        type: "tuple",
                                    },
                                ],
                                internalType: "struct TokenInfoAggregator.V2PairInfo",
                                name: "v2WbnbQuotePair",
                                type: "tuple",
                            },
                        ],
                        internalType: "struct TokenInfoAggregator.PoolInfo",
                        name: "pool",
                        type: "tuple",
                    },
                ],
                internalType: "struct TokenInfoAggregator.FourmemeTokenInfo",
                name: "",
                type: "tuple",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "token", type: "address" }],
        name: "getTokenQuote",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "token", type: "address" }],
        name: "getTokenTradingStatus",
        outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "token", type: "address" }],
        name: "isFourmemeToken",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "view",
        type: "function",
    },
];
export const AGGREGATOR_CONTRACT = "0xebbffa21c6d1a2ca2e2e29ddc58312549223fdbb";
export const ERC20_ABI = [
    {
        inputs: [
            { name: "spender", type: "address" },
            { name: "amount", type: "uint256" },
        ],
        name: "approve",
        outputs: [{ name: "", type: "bool" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { name: "owner", type: "address" },
            { name: "spender", type: "address" },
        ],
        name: "allowance",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ name: "account", type: "address" }],
        name: "balanceOf",
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
];
